export default  {
    products: [
      {
        id: 1,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "Shirts",
        price: "$60",
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
      },
      {
        id: 2,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "pants",
        price: "$50",
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
      },
      {
        id: 3,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "Shirts",
        price: "$60",
        brand: "Nike",
        rating: 4.2,
        numReviews: 10,
      },
      {
        id: 4,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "Shirts",
        price: "$60",
        brand: "Nike",
        rating: 4,
        numReviews: 10,
      },
      {
        id: 6,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "Shirts",
        price: "$60",
        brand: "Nike",
        rating: 4.5,
        numReviews: 4,
      },
      {
        id: 7,
        name: "Slim Shirt",
        image: "/images/s1.jpg",
        catagorey: "Shirts",
        price: "$60",
        brand: "Nike",
        rating: 4.5,
        numReviews: 5,
      },
    ],
  };
  
  